WIP: Compilation mode similar to upstream
Currently fails with
RuntimeError: Worker failed with error 'Unsupported: Spyre backend does not support: to_dtype on DataFormats.IEEE_FP32

Signed-off-by: Thomas Ortner <boh@zurich.ibm.com>